
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Author extends ContentItem {
    public portrait?: Elements.AssetsElement;
    public name?: Elements.TextElement;
    public untitledUrlSlug?: Elements.UrlSlugElement;
    public bio?: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'url_slug') {
                    return 'urlSlug';
                }
                if (elementName === 'untitled_url_slug') {
                    return 'untitledUrlSlug';
                }
                return elementName;
            })
        });
    }
}
